#!/usr/bin/perl
use Cwd;
use strict;

my $cxx;
my $ccorcxx;
if ($ARGV[0] ne '++') {
    $ccorcxx = 'CC';
    $cxx = 0;
} else {
    shift @ARGV;
    $ccorcxx = 'CXX';
    $cxx = 1;
}
die "$0: $ccorcxx environment variable does not exist\n" unless exists $ENV{$ccorcxx};

my @compiler = split ' ', $ENV{$ccorcxx};

if ("@ARGV" !~ / -nostdinc/o) {
    push @compiler, '-nostdinc';
    push @compiler, '-I' . $_ for split ' ', $ENV{CCWRAP_HEADERS};
    push @compiler, '-isystem', $_ for split ' ', $ENV{CCWRAP_SYSTEM_HEADERS};
    push @compiler, '-isystem', $_ for split ' ', $ENV{CCWRAP_COMPILER_HEADERS};
    push @compiler, '-isystem', $_ for split ' ', $ENV{CCWRAP_DIRAFTER_HEADERS}
} else {
    die "$0: -nostdinc was used\n";
}

push @compiler, @ARGV;

exec @compiler or die "$0: $compiler[0] failed to execute\n";
